name: 'Run sonar quality gate'
description: 'Run sonar quality gate on a PR or branch'

inputs:
  sonar-token:
    description: "Sonarqube access token"
    required: true

runs:
  using: "composite"
  steps:
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      if: ${{ github.event_name == 'pull_request' }}
      uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # pin@v1.2.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        scanMetadataReportFile: ${{ github.workspace }}/build/sonar/report-task.txt