name: 'Push git tag'
description: 'Pushes the latest created tag to remote'

inputs:
  version-name:
    description: 'Version name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Git tag bundles
      run: |
        git tag -a "v${INPUT_VERSION_NAME}" -m "Creating tag v${INPUT_VERSION_NAME}"
        git push origin "v${INPUT_VERSION_NAME}"
      shell: bash
      env:
        INPUT_VERSION_NAME: ${{ inputs.version-name }}
