name: 'Bundle reports'
description: 'Zip and upload build reports'

runs:
  using: "composite"
  steps:
    - name: Bundle build reports
      id: bundleReports
      run: |
        zip -9 -r reports.zip **/build/reports
      shell: bash

    - name: Upload build reports
      id: uploadBuildReports
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: build-reports
        retention-days: 1
        if-no-files-found: error
        path: |-
          reports.zip
