name: 'Bundle reports'
description: 'Zip and upload build reports'

runs:
  using: "composite"
  steps:
    - name: Bundle build reports
      id: bundleReports
      run: |
        zip -9 -r reports.zip **/build/reports
      shell: bash

    - name: Upload build reports
      id: uploadBuildReports
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: build-reports
        retention-days: 1
        if-no-files-found: error
        path: |-
          reports.zip
