name: Cache mobile-android-pipelines build
description: Caches the build for Gradle plugins and build logic

runs:
  using: "composite"
  steps:
  - name: Get mobile-android-pipelines commit
    run: echo "PIPELINES_COMMIT=$(git rev-parse HEAD:mobile-android-pipelines)" >> $GITHUB_ENV
    shell: bash

  - name: Cache mobile-android-pipelines build
    uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
    with:
      key: mobile-android-pipelines-build-${{ env.PIPELINES_COMMIT }}
      path: |
        mobile-android-pipelines/buildLogic/**/build/**/*
        mobile-android-pipelines/buildLogic/.gradle/**/*
