name: 'Setup Runner'
description: 'Set up GitHub Runner environment for building the Android OneLogin app'
inputs:
  jdk-version:
    description: 'The Java Development Kit (JDK) version to use'
    required: false
    default: '21'
  gradle-version:
    description: 'The version of gradle for the "gradle/gradle-build-action" step.'
    required: false
    default: 'wrapper'
runs:
  using: "composite"
  steps:
    - name: Add path globally
      shell: bash
      run: echo "/usr/local/bin" >> $GITHUB_PATH

    - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
      with:
        distribution: 'oracle'
        java-version: ${{ inputs.jdk-version }}

    - name: Add JAVA_HOME globally
      env:
        JDK_VERSION: ${{ inputs.jdk-version }}
      run: |
        echo "JAVA_HOME=$(/usr/libexec/java_home --version ${JDK_VERSION})" >> $GITHUB_ENV
      shell: bash

    # - name: Install snap dependencies
    #   run: |
    #     sudo snap install vale --edge
    #   shell: bash
    #   if: runner.os == 'Linux'

    - name: Install homebrew if necessary

      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      shell: bash

    - name: Install brew dependencies
      run: |
        source ./config/shell/brewPath
        brew bundle
      shell: bash

    - name: Update
      run: |
        sudo apt-get update
      shell: bash
      if: runner.os == 'Linux'

    - name: Install Linux Dependencies
      run: |
        sudo apt-get install $(grep -o '^[^#]*' ./Aptfile)
      shell: bash
      if: runner.os == 'Linux'

    # https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
    - name: Configure KVM hardware acceleration
      run: echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
      shell: bash
      if: runner.os == 'Linux'

    - name: Modify KVM groups / rules
      run: |
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        sudo adduser $(id -un) libvirt
        sudo adduser $(id -un) kvm
      shell: bash
      if: runner.os == 'Linux'

    - name: Confirm KVM hardware acceleration is installed
      run: |
        kvm-ok
        egrep --count '(vmx|svm)' /proc/cpuinfo
      shell: bash
      if: runner.os == 'Linux'

    - name: Setup Gradle
      id: setupGradle
      uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
      env:
        CI: 'true'
      with:
        gradle-version: ${{ inputs.gradle-version }}
        cache-disabled: true

    - name: Setup Android SDK
      uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # pin@v2

    - name: Update Android SDK Manager
      run: |
        sdkmanager --update
      shell: bash

    - name: git
      run: |
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git status
        git tag
        git describe
      shell: bash
      if: runner.os == 'Linux'
