name: 'Get next version from commit message'
description: 'Gets the next version number from the release branch when merging into main'

outputs:
  next-version:
    description: 'Next version number determined from the commit message when release branch merged into main'
    value: ${{ steps.get-latest-tag.outputs.next-version }}
  next-version-pattern:
    description: 'Pattern used in git describe calls for the next version number'
    value: ${{ steps.get-next-version.outputs.next-version-pattern }}

runs:
  using: "composite"
  steps:
    - name: Get latest tagged version
      id: get-latest-tag-from-commit-msg
      run: |
        echo "$(git log --oneline -n 5)"
        commit_title=$(git log -1 --pretty=%s | tail -n1)
        
        merged_branch=$(echo "$commit_title" | head -n1)
        IFS=/ read -r BRANCH_PREFIX BRANCH_SUFFIX BRANCH_VERSION <<< "${merged_branch}"
        
        if [[ "$BRANCH_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
        then
          NEXT_VERSION="${BASH_REMATCH[0]}"
        else
          echo "Invalid version in branch name ($commit_title)"
          exit 1
        fi
        
        echo "NEXT_VERSION = $NEXT_VERSION"
        
        echo "next-version=$NEXT_VERSION" >> $GITHUB_OUTPUT
        
        IFS=. read -r MAJOR MINOR PATCH <<< $NEXT_VERSION
        
        echo "next-version-pattern=v${MAJOR}.${MINOR}.*" >> $GITHUB_OUTPUT
      shell: bash
