name: Bump version

on:
  workflow_run:
    workflows: [Test]
    branches: [main]
    types: [completed]
  workflow_dispatch:

env:
  WORKFLOW_OUT_DIR: ./workflow-outputs

jobs:
  bump-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      JDK_VERSION: 21
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout github action
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup GitHub Runner workflow
        uses: ./mobile-android-pipelines/actions/setup-runner
        with:
          jdk-version: 21

      - name: Increment the release version using Conventional Commits
        id: versioning
        uses: ./mobile-android-pipelines/actions/increment-version

      - name: Publish release tags
        if: ${{ steps.versioning.outputs.current_version != steps.versioning.outputs.new_version }}
        uses: ./mobile-android-pipelines/actions/publish-release-tag

      - name: Generate Changelog
        uses: ./mobile-android-pipelines/actions/generate-and-upload-changelog
        with:
          current-version: ${{ steps.versioning.outputs.current_version }}
          new-version: ${{ steps.versioning.outputs.new_version }}
          version-prefix: ''

      - name: Create workflow outputs
        env:
          VERSION_BUMPED: ${{ steps.versioning.outputs.current_version != steps.versioning.outputs.new_version }}
        run: |
          mkdir "$WORKFLOW_OUT_DIR" && touch "$WORKFLOW_OUT_DIR/bump-version.yml"
          yq -i ".version-bumped = $VERSION_BUMPED" "$WORKFLOW_OUT_DIR/bump-version.yml"
        shell: bash

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bump-version-outputs
          path: ${{env.WORKFLOW_OUT_DIR}}/**

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace
