name: Dependency Submission

on:
  push:
    branches: ['main']

permissions:
  contents: read
  security-events: write
  id-token: write
  actions: read

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.MODULE_FETCH_TOKEN }}
      USERNAME: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
