name: On Branch Push (release)

on:
  push:
    branches:
      - "release/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepareForRelease:
    name: Verify code base when pushed
    runs-on: ubuntu-24.04
    #    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      packages: read
      id-token: write
      contents: read
    outputs:
      version: ${{ steps.version-number.outputs.version }}
    steps:
      - name: Run checkout github action
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Detect Arch
        id: detect-arch
        uses: ./config/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Retrieve secrets
        uses: ./config/actions/retrieve-secrets
        with:
          actions-role-arn: ${{ secrets.GITHUBRUNNER_EC2_ACTIONS_ROLE_ARN }}

      - name: Get latest tag
        id: latest-tag
        uses: ./config/actions/get-latest-tag
        with:
          pattern: 'v*'

      - name: Get next version from branch
        id: next-version
        uses: ./config/actions/get-next-version-from-branch

#      - name: Ensure version is correct
#        id: version-number
#        uses: ./config/actions/ensure-version-is-correct
#        with:
#          current-version: ${{ steps.latest-tag.outputs.current-tag }}
#          next-version: ${{ steps.next-version.outputs.next-version }}

      - name: Display version jump
        run: |
          echo "Moving from $CURRENT_VERSION to $NEXT_VERSION"
        shell: bash
        env:
          CURRENT_VERSION: ${{ steps.latest-tag.outputs.current-tag }}
          NEXT_VERSION: ${{ steps.next-version.outputs.next-version }}
#          NEXT_VERSION: ${{ steps.version-number.outputs.version }}

  buildAndPublishRelease:
    name: Verify code base when pushed
    needs: prepareForRelease
    runs-on: ubuntu-22.04
    environment: release
    permissions:
      contents: write
      packages: read
      id-token: write
    steps:
      - name: Run checkout github action
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Detect Arch
        id: detect-arch
        uses: ./config/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Retrieve secrets
        uses: ./config/actions/retrieve-secrets
        with:
          actions-role-arn: ${{ secrets.GITHUBRUNNER_EC2_ACTIONS_ROLE_ARN }}

      - name: Generate version code
        id: version-code
        uses: ./config/actions/generate-version-code

      - name: Bundle release
        id: bundle-release
        uses: ./config/actions/gradle-assemble-and-bundle
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          module-fetch-token: ${{ secrets.MODULE_FETCH_TOKEN }}
#          flavors: 'staging,integration,production'
          flavors: 'build, staging'
          github-actor: ${{ secrets.GITHUB_ACTOR }}
          module-fetch-token-username: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ needs.prepareForRelease.outputs.version }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Upload to play store
        uses: ./config/actions/upload-to-play-store
        with:
          aab-paths: ${{ steps.bundle-release.outputs.aab-paths }}

      - name: Git tag bundles
        uses: ./config/actions/git-tag-bundles-release
        with:
          aab-paths: ${{ steps.bundle-release.outputs.aab-paths }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ needs.prepareForRelease.outputs.version }}

      - name: Clean workspace
        if: always()
        uses: ./config/actions/clean-workspace
