name: On Branch Push (main)

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onPushMain:
    name: Verify code base when pushed
    runs-on: ubuntu-24.04
    #    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      packages: read
      id-token: write
      contents: read
    steps:
      - name: Run checkout github action
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Detect Arch
        id: detect-arch
        uses: ./config/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Retrieve secrets
        uses: ./config/actions/retrieve-secrets
        with:
          actions-role-arn: ${{ secrets.GITHUBRUNNER_EC2_ACTIONS_ROLE_ARN }}

      - name: Get latest tag
        id: latest-tag
        uses: ./config/actions/get-latest-tag
        with:
          pattern: 'v*'

      - name: Get next version from last commit
        id: next-version
        uses: ./config/actions/get-next-version-from-commit-message

      - name: Ensure version is correct
        id: version-number
        uses: ./config/actions/ensure-version-is-correct
        with:
          current-version: ${{ steps.latest-tag.outputs.current-tag }}
          next-version: ${{ steps.next-version.outputs.next-version }}

      - name: Display version jump
        run: |
          echo "Moving from $CURRENT_VERSION to $NEXT_VERSION"
          shell: bash
        env:
          CURRENT_VERSION: ${{ steps.latest-tag.outputs.current-tag }}
          NEXT_VERSION: ${{ steps.version-number.outputs.version }}

      - name: Push tag
        id: git-tag
        uses: ./config/actions/push-tag
        env:
          NEXT_VERSION: ${{ steps.version-number.outputs.version }}

      - name: Generate version code
        id: version-code
        uses: ./config/actions/generate-version-code

      - name: Run gradle instrumentation tests
        uses: ./config/actions/gradle-connected-test-managed
        with:
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: "${{ steps.latest-tag.outputs.current-tag }}-${{ steps.version-code.outputs.version-code }}"
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Run gradle unit tests
        uses: ./config/actions/gradle-check
        with:
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: "${{ steps.latest-tag.outputs.current-tag }}-${{ steps.version-code.outputs.version-code }}"
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Run sonar analysis
        uses: ./config/actions/sonar-analysis
        with:
          project-version: ${{ steps.version-name.outputs.version-name }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Clean workspace
        if: always()
        uses: ./config/actions/clean-workspace
