name: On Branch Push (main)

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-up-and-publish:
    name: Verify code base when pushed
    runs-on: ubuntu-24.04
    #    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    outputs:
      version-code: ${{ steps.version-code.outputs.version-code }}
      version-name: ${{ steps.version-number.outputs.version }}
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      packages: read
      id-token: write
      contents: write
    steps:
      - name: Run checkout github action
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Detect Arch
        id: detect-arch
        uses: ./config/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Retrieve secrets
        uses: ./config/actions/retrieve-secrets
        with:
          actions-role-arn: ${{ secrets.GITHUBRUNNER_EC2_ACTIONS_ROLE_ARN }}

      - name: Get latest tag
        id: latest-tag
        uses: ./config/actions/get-latest-tag
        with:
          pattern: 'v*'

      - name: Get next version from last commit
        id: next-version
        uses: ./config/actions/get-next-version-from-commit-message

      - name: Ensure version is correct
        id: version-number
        uses: ./config/actions/ensure-version-is-correct
        with:
          current-version: ${{ steps.latest-tag.outputs.current-tag }}
          next-version: ${{ steps.next-version.outputs.next-version }}

      - name: Display version jump
        run: |
          echo "Moving from $CURRENT_VERSION to $NEXT_VERSION"
        shell: bash
        env:
          CURRENT_VERSION: ${{ steps.latest-tag.outputs.current-tag }}
          NEXT_VERSION: ${{ steps.version-number.outputs.version }}

      - name: Push tag
        id: git-tag
        uses: ./config/actions/push-tag
        with:
          version-name: ${{ steps.version-number.outputs.version }}

      - name: Generate version code
        id: version-code
        uses: ./config/actions/generate-version-code

      - name: Bundle release
        id: bundle-release
        uses: ./config/actions/gradle-assemble-and-bundle
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          module-fetch-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          flavors: 'production'
          github-actor: ${{ secrets.GITHUB_ACTOR }}
          module-fetch-token-username: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-number.outputs.version }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Upload to play store
        uses: ./config/actions/upload-to-play-store
        with:
          aab-paths: ${{ steps.bundle-release.outputs.aab-paths }}

      - name: Git tag bundles
        uses: ./config/actions/git-tag-bundles
        with:
          aab-paths: ${{ steps.bundle-release.outputs.aab-paths }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-number.outputs.version }}

  run-instrumentation-tests:
    name: Verify code base when pushed
    runs-on: ubuntu-24.04
    needs:
      - set-up-and-publish
    #    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      packages: read
      id-token: write
      contents: write
    steps:
      - name: Run gradle instrumentation tests
        uses: ./config/actions/gradle-connected-test-managed
        with:
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ needs.set-up-and-publish.outputs.version-code }}
          version-name: ${{ needs.set-up-and-publish.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

  run-unit-tests:
    name: Verify code base when pushed
    runs-on: ubuntu-24.04
    needs:
      - set-up-and-publish
    #    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      packages: read
      id-token: write
      contents: write
    steps:
      - name: Run gradle unit tests
        uses: ./config/actions/gradle-check
        with:
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ needs.set-up-and-publish.outputs.version-code }}
          version-name: ${{ needs.set-up-and-publish.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

  run-sonar-analysis:
    name: Verify code base when pushed
    runs-on: ubuntu-24.04
    needs:
      - set-up-and-publish
      - run-instrumentation-tests
      - run-unit-tests
    #    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      packages: read
      id-token: write
      contents: write
    steps:
      - name: Run sonar analysis
        uses: ./config/actions/sonar-analysis
        with:
          project-version: ${{ steps.version-name.outputs.version-name }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          version-code: ${{ needs.set-up-and-publish.outputs.version-code }}
          version-name: ${{ needs.set-up-and-publish.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Clean workspace
        if: always()
        uses: ./config/actions/clean-workspace
