name: On Branch Push (develop)

on:
  push:
    branches:
      - "develop"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write

jobs:
  onPushDevelopJob:
    name: Verify code base when pushed
    runs-on: ubuntu-24.04
    #    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      id-token: write
      contents: write
      packages: read
    steps:
      - name: Run checkout github action
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Detect Arch
        id: detect-arch
        uses: ./config/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Retrieve secrets
        uses: ./config/actions/retrieve-secrets
        with:
          actions-role-arn: ${{ secrets.GITHUBRUNNER_EC2_ACTIONS_ROLE_ARN }}

      - name: Get latest tag
        id: latest-tag
        uses: ./config/actions/get-latest-tag
        with:
          pattern: 'v*'

      - name: Generate version code
        id: version-code
        uses: ./config/actions/generate-version-code

      - name: Generate version name
        id: version-name
        uses: ./config/actions/version-name
        with:
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.latest-tag.outputs.current-tag }}

      - name: Bundle release
        id: bundle-release
        uses: ./config/actions/gradle-assemble-and-bundle
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          module-fetch-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          flavors: 'production,integration,build,staging'
          github-actor: ${{ secrets.GITHUB_ACTOR }}
          module-fetch-token-username: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Encrypt int bundle and upload for it to github artifacts
        id: encryptIntBundle
        run: |
          gpg --import temp_app_bundle_signing_key_pub.gpg
          gpg --batch --yes \
          --trust-model always \
          --pinentry-mode loopback \
          --recipient bianca.mihaila@digital.cabinet-office.gov.uk \
          --encrypt \
          --output encrypted-int-bundle.aab.gpg \
          integration:app/build/outputs/bundle/integrationRelease/app-integration-release.aab;

      - name: Encrypt prod bundle and upload for it to github artifacts
        id: encryptProdBundle
        run: |
          gpg --import temp_app_bundle_signing_key_pub.gpg
          gpg --batch --yes \
          --trust-model always \
          --pinentry-mode loopback \
          --recipient bianca.mihaila@digital.cabinet-office.gov.uk \
          --encrypt \
          --output encrypted-prod-bundle.aab.gpg \
          production:app/build/outputs/bundle/productionRelease/app-production-release.aab;

      - name: Bundle encrypted files
        id: bundleEncryptedFiles
        run: |
          zip -9 -r encrypted-prod-bundle.zip encrypted-prod-bundle.aab.gpg
          zip -9 -r encrypted-int-bundle.zip encrypted-int-bundle.aab.gpg

        shell: bash

      - name: Upload encrypted bundles prod
        id: uploadEncryptedProdFile
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: encryptedProdBundle
          retention-days: 1
          if-no-files-found: error
          path: |-
            encrypted-prod-bundle.zip

      - name: Upload encrypted bundles int
        id: uploadEncryptedIntFile
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: encryptedIntBundle
          retention-days: 1
          if-no-files-found: error
          path: |-
            encrypted-int-bundle.zip 

      - name: Run gradle instrumentation tests
        uses: ./config/actions/gradle-connected-test-managed
        with:
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: "${{ steps.latest-tag.outputs.current-tag }}-${{ steps.version-code.outputs.version-code }}"
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Run gradle unit tests
        uses: ./config/actions/gradle-check
        with:
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: "${{ steps.latest-tag.outputs.current-tag }}-${{ steps.version-code.outputs.version-code }}"
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Run sonar analysis
        uses: ./config/actions/sonar-analysis
        with:
          project-version: ${{ steps.version-name.outputs.version-name }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Upload to play store
        uses: ./config/actions/upload-to-play-store
        with:
          aab-paths: ${{ steps.bundle-release.outputs.aab-paths }}

      - name: Git tag bundles
        uses: ./config/actions/git-tag-bundles
        with:
          aab-paths: ${{ steps.bundle-release.outputs.aab-paths }}
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}

      - name: Clean workspace
        if: always()
        uses: ./config/actions/clean-workspace
