# When making structure changes to the workflow, please ensure the quality-gate.manifest.json is updated accordingly to reflect this.
name: On Schedule (default branch)

on:
  schedule:
    - cron: 0 3 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-up:
    name: Set-up and generate version name and version code
    runs-on: ubuntu-22.04
    outputs:
      version-code: ${{ steps.version-code.outputs.version-code }}
      version-name: ${{ steps.version-name.outputs.version-name }}

    steps:
      - name: Run checkout github action
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Get latest tag
        id: latest-tag
        uses: ./config/actions/get-latest-tag
        with:
          pattern: 'v*'

      - name: Generate version code
        id: version-code
        uses: ./mobile-android-pipelines/actions/generate-version-code

      - name: Generate version name
        id: version-name
        uses: ./mobile-android-pipelines/actions/version-name
        with:
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.latest-tag.outputs.current-tag }}

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace
  style-checks:
    name: Run style (detekt, lint & vale) checks
    runs-on: ubuntu-22.04
    needs:
      - set-up
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      contents: read
      packages: read

    steps:
      - name: Run checkout github action
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup prerequisite dependencies
        uses: ./mobile-android-pipelines/actions/common-prerequisites

      - name: Setup GitHub Runner workflow
        uses: ./mobile-android-pipelines/actions/setup-runner

      - name: Clean runner
        uses: ./mobile-android-pipelines/actions/clean-runner-fast

      - name: Run gradle style checks (Detekt, Lint, Vale)
        id: style-checks
        uses: ./config/actions/gradle-checks
        with:
          test-type: "style"
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ needs.set-up.outputs.version-code }}
          version-name: ${{ needs.set-up.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Upload ktlint coverage report
        uses: ./mobile-android-pipelines/actions/upload-coverage-reports
        with:
          artifact-name: ktlint-reports
          path: "**/build/reports/ktlint/**/*.xml"

      - name: Upload detekt coverage report
        uses: ./mobile-android-pipelines/actions/upload-coverage-reports
        with:
          artifact-name: detekt-reports
          path: "**/build/reports/detekt/**/*.xml"

      - name: Upload lint coverage report
        uses: ./mobile-android-pipelines/actions/upload-coverage-reports
        with:
          artifact-name: lint-reports
          path: "**/build/reports/lint-results*.xml"

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace

  instrumentation-checks:
    name: Run instrumentation tests
    runs-on: ubuntu-22.04
    needs:
      - set-up
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      contents: read
      packages: read

    steps:
      - name: Run checkout github action
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup GitHub Runner workflow
        uses: ./mobile-android-pipelines/actions/setup-runner

      - name: Clean runner
        uses: ./mobile-android-pipelines/actions/clean-runner-fast

      - name: Run gradle instrumentation tests
        id: instrumentation-tests
        uses: ./config/actions/gradle-connected-test-managed
        with:
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ needs.set-up.outputs.version-code }}
          version-name: ${{ needs.set-up.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Upload instrumentation test coverage report
        uses: ./mobile-android-pipelines/actions/upload-coverage-reports
        with:
          artifact-name: instrumentation-reports
          path: "**/build/reports/jacoco/managed/**/*.xml"

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace

  component-checks:
    name: Run component tests
    runs-on: ubuntu-22.04
    needs:
      - set-up
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      contents: read
      packages: read

    steps:
      - name: Run checkout github action
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup GitHub Runner workflow
        uses: ./mobile-android-pipelines/actions/setup-runner

      - name: Clean runner
        uses: ./mobile-android-pipelines/actions/clean-runner-fast

      - name: Run gradle component tests
        id: component-test
        uses: ./config/actions/gradle-checks
        with:
          test-type: "component"
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ needs.set-up.outputs.version-code }}
          version-name: ${{ needs.set-up.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Upload component test coverage report
        uses: ./mobile-android-pipelines/actions/upload-coverage-reports
        with:
          artifact-name: component-reports
          path: "**/build/reports/jacoco/**/*.xml"

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace

  unit-checks:
    name: Run unit tests
    runs-on: ubuntu-22.04
    needs:
      - set-up
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      contents: read
      packages: read

    steps:
      - name: Run checkout github action
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup GitHub Runner workflow
        uses: ./mobile-android-pipelines/actions/setup-runner

      - name: Clean runner
        uses: ./mobile-android-pipelines/actions/clean-runner-fast

      - name: Run gradle unit tests
        id: unit-test
        uses: ./config/actions/gradle-checks
        with:
          test-type: "unit"
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ needs.set-up.outputs.version-code }}
          version-name: ${{ needs.set-up.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Upload unit test coverage report
        uses: ./mobile-android-pipelines/actions/upload-coverage-reports
        with:
          artifact-name: unit-reports
          path: "**/build/reports/jacoco/**/*.xml"

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace

  snapshot-checks:
    name: Run snapshot/ screenshot tests
    runs-on: ubuntu-22.04
    needs:
      - set-up
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      contents: read
      packages: read

    steps:
      - name: Run checkout github action
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup GitHub Runner workflow
        uses: ./mobile-android-pipelines/actions/setup-runner

      - name: Clean runner
        uses: ./mobile-android-pipelines/actions/clean-runner-fast

      - name: Run gradle snapshot tests
        id: snapshot-test
        uses: ./config/actions/gradle-checks
        with:
          test-type: "snapshot"
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          version-code: ${{ needs.set-up.outputs.version-code }}
          version-name: ${{ needs.set-up.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace

  sonar-analysis:
    name: Run sonar analysis and check sonar quality gate
    runs-on: ubuntu-22.04
    needs:
      - set-up
      - style-checks
      - unit-checks
      - component-checks
      - snapshot-checks
      - instrumentation-checks
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      contents: read
      packages: read

    steps:
      - name: Run checkout github action
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup GitHub Runner workflow
        uses: ./mobile-android-pipelines/actions/setup-runner

      - name: Clean runner
        uses: ./mobile-android-pipelines/actions/clean-runner-fast

      - name: Restore coverage reports to build directories
        uses: ./mobile-android-pipelines/actions/restore-coverage-reports

      - name: Run sonar analysis
        uses: ./config/actions/sonar-analysis
        with:
          project-version: ${{ steps.version-name.outputs.version-name }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          version-code: ${{ needs.set-up.outputs.version-code }}
          version-name: ${{ needs.set-up.outputs.version-name }}
          app-check-token: ${{ secrets.BUILD_APPCHECK_DEBUG_TOKEN }}
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}

      - name: Bundle reports folder
        uses: ./mobile-android-pipelines/actions/bundle-reports

      - name: Run sonar quality gate
        uses: ./config/actions/sonar-quality-gate
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace
