name: Check PR metadata

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title against conventional commit standards
        uses: Oliver-Binns/Versioning@768ec693878abe2f357b151572915d2ab654d13e # 1.3.2
        with:
          ACTION_TYPE: 'Validate'

  check-commit-messages:
    name: Check commit messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0
          # Check the PR HEAD instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check commit messages
        uses: ./mobile-android-pipelines/actions/verify-conventional-commit
