name: Upload to Play Store

on:
  workflow_run:
    workflows: [Bump version]
    branches: [main]
    types: [completed]
  workflow_dispatch:

jobs:
  upload-to-play-store:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      JDK_VERSION: 21
    runs-on: ubuntu-latest
    permissions:
      # Set permissions for ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      packages: read
    steps:
      - name: Run checkout github action
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0

      - name: Setup GitHub Runner workflow
        uses: ./mobile-android-pipelines/actions/setup-runner
        with:
          jdk-version: 21

      - name: Cache mobile-android-pipelines build
        uses: ./actions/cache-pipelines-build

      - name: Retrieve GitHub secrets
        id: retrieve-secrets
        uses: ./mobile-android-pipelines/actions/retrieve-secrets
        with:
          keystore-base64: ${{ secrets.KEYSTORE_BASE64 }}
          google-service-account-json-base64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64 }}

      - name: Generate version code
        id: generate-version-code
        uses: ./mobile-android-pipelines/actions/generate-version-code

      - name: Bundle release app
        id: bundle-release-app
        uses: ./mobile-android-pipelines/actions/bundle-release-app
        with:
          github-actor: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME }}
          github-token: ${{ secrets.MODULE_FETCH_TOKEN }}
          keystore-file-path: ${{ steps.retrieve-secrets.outputs.keystore-file-path }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          keystore-key-alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          keystore-key-password: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          modules: 'app'
          flavors: 'staging,build,production,integration'
          version-code: ${{ steps.generate-version-code.outputs.version-code }}

      - name: Upload to Play Store
        uses: ./mobile-android-pipelines/actions/publish-to-play-store
        with:
          aab-paths: ${{ steps.bundle-release-app.outputs.aab-paths }}
          package-name: 'uk.gov.onelogin'
          google-service-account-json: ${{ steps.retrieve-secrets.outputs.google-service-account-json-file-path }}

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace
